# 操作文件

## 读取文件loadtxt()，读取txt文件，csv文件
   loadtxt(fname,dtype,comments,delimiter,converters,skiprows,usercols,unpack,ndmin,encoding)
   
   comments：字符串或字符串组成的列表，表示注释字符集开始的标志，默认为#
   
   delimiter：字符串。分隔符
   
   converters：字典 。将特定列的数据转换为字典中对应的函数的浮点型数据。
   
   skiprows：跳过特定行数据
   
   usercols：元组，用来指定要读取数据的列
   
   unpack：布尔型。指定是否转置数组
   
   ndmin：整数型，指定返回的数组至少包含特定维度的数组
   
   encoding：编码

## 读取普通文件

In [2]:
import numpy as np

In [3]:
data = np.loadtxt('file/data1.txt')
print(data,data.shape)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]] (3, 10)


In [5]:
# 读取csv文件，需要设置分隔符，否则读出字符串，无法转为整型数据
data = np.loadtxt('file/csv_test.csv',dtype = np.int32,delimiter = '\t')
print(data,data.shape)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]] (3, 10)


In [6]:
# 读取结构化的数据
user_info = np.dtype([('name','U10'),('age','i1'),('gender','U1'),('height','i2')])

data = np.loadtxt('file/has_title.txt',dtype = user_info,skiprows = 1,encoding = 'utf-8')
print(data)

[('小王', 21, '男', 170) ('小张', 25, '女', 165) ('小花', 19, '女', 197)]


In [7]:
# 计算平均年龄
ages = data['age']
print(ages)
ages.mean()

[21 25 19]


21.666666666666668

In [8]:
# 如果只需要获取年龄，则可以用另一种方法
data = np.loadtxt('file/has_title.txt',dtype = 'i1',usecols = 1,skiprows = 1,encoding = 'utf-8')
data

array([21, 25, 19], dtype=int8)

In [9]:
# 计算女生的平均身高
data = np.loadtxt('file/has_title.txt',dtype = user_info,skiprows = 1,encoding = 'utf-8')

isgirl = data['gender'] == '女'
print(isgirl)
print(data['height'])
print(data['height'][isgirl])
print(data['height'][isgirl].mean())

[False  True  True]
[170 165 197]
[165 197]
181.0


## 对于空置或其他异常值的处理

In [ ]:
# 使用converterss