# 切片和索引
- ndarray对象的内容可以通过索引或切片来访问和修改，与原生python中的list的切片操作一样
- 与原生python中的list不同的是，ndarray对象的切片会改变原始数组

In [1]:
import numpy as np

In [2]:
ar1 = np.arange(10)
ar2 = ar1[2:7:2] # 不包含终止值
print(ar1)
print(ar2)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [3]:
# 与原生python不同之处
ar1[2] = 10
ar2

array([10,  4,  6])

## 二维数组的切片方法

In [6]:
ar3 = np.arange(20).reshape((4,5))
ar3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
ar3.ndim

2

In [8]:
ar3[2]

array([10, 11, 12, 13, 14])

In [11]:
ar3[2:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

- 切片还可以使用省略号'...'，如果在行位置使用省略号，则返回值包含所有的行元素

In [12]:
ar3[...,1]

array([ 1,  6, 11, 16])

In [15]:
ar3[...,1:]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [14]:
ar3[...,...] # 只可以有一个省略号

IndexError: an index can only have a single ellipsis ('...')

In [16]:
ar3[1,2] == ar3[1][2] #虽然返回值相同，但是底层的查找逻辑不同。
# 前者使用坐标查找法，寻找交叉点，后者是先取行，再从行列表中找到第3个元素

True

In [17]:
ar3[...][1] # 注意这个逻辑 等价于ar3[1]

array([5, 6, 7, 8, 9])

In [18]:
ar3[...][1][2] #

7

In [2]:
x = np.array([[1,2],[3,4],[5,6]])
y = x[[0,1,2],[0,1,0]] # [0,1,2]代表行索引，[0,1,0]代表列索引
y

array([1, 4, 5])

In [5]:
b = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
a = b[[0,0,3,3],[0,2,0,2]]
print(a.reshape((2,2)))

r = np.array([[0,0],[3,3]]).reshape(4)
l = np.array([[0,2],[0,2]]).reshape(4)
s = b[r,l].reshape((2,2))
print(r)
print(l)
print(s)

[[ 0  2]
 [ 9 11]]
[0 0 3 3]
[0 2 0 2]
[[ 0  2]
 [ 9 11]]


In [7]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = a[1:3,1:3]
print(b)
c = a[1:3,[1,2]]
print(c)
d = a[...,1:]
print(d)

[[5 6]
 [8 9]]
[[5 6]
 [8 9]]
[[2 3]
 [5 6]
 [8 9]]


In [14]:
# 创建一个8 x 8的国际象棋棋盘，用0表示黑块，1表示白块、
z = np.zeros((8,8),dtype = int)
print(z)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [15]:
z[1::2,::2] = 1
print(z)

[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]


In [16]:
z[::2,1::2] = 1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 布尔索引

In [3]:
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
x[x > 6]

array([ 7,  8,  9, 10, 11])

In [4]:
# 提取上个数组中所有的奇数
x[x % 2 == 1]

array([ 1,  3,  5,  7,  9, 11])

In [5]:
# 并将所有的奇数值修改为-1
x[x % 2 == 1] = -1
print(x)

[[ 0 -1  2]
 [-1  4 -1]
 [ 6 -1  8]
 [-1 10 -1]]


In [9]:
# & 表示与，| 表示或，与原生的python不同，注意区分
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x[(x > 4) & (x < 9)])

[5 6 7 8]


### 用True与False表示需要与不需要的元素

In [17]:
ar1 = np.arange(12).reshape((3,4))
ar1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
row1 = np.array([False,True,True])
col1 = np.array([True,False,True,False])

In [15]:
ar1[row1]
# ar1[[1,2]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
ar1[...,col1]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

### 注意索引数组不匹配的问题

In [21]:
ar1[[1,2],[0,1,2]]
# x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
# 前后索引数组形状不同

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [22]:
# 选择ar1的首行和尾行的1，3，4列元素
ar1[[0,-1],[0,2,3]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [23]:
# 先选取行，在选取列
temp = ar1[[0,-1],...]
temp

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [24]:
temp[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 8, 10, 11]])

In [30]:
# 与上述过程等价
ar1[[0,-1],:][:,[0,2,3]]

array([[ 0,  2,  3],
       [ 8, 10, 11]])

In [31]:
# 以这个例子来认识索引与切片的不同
ar1[:3:2,[0,2,3]]

array([[ 0,  2,  3],
       [ 8, 10, 11]])

## 广播机制
   广播(Broadcast)是numpy对不同形状的数组进行数值计算的方式，对数组的算数运算通常在相应的元素上进行。
   
   如果两个数组a和b形状相同，即满足a.shape == b.shape，那么a*b的结果就是a与b数组对应位相乘。这要求维数相同，且各维度的长度相同。

In [32]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a * b
print(c)

[ 10  40  90 160]


当两个形状不同的数组相乘时，会令形状较小的数组，在其他维度上进行一定的重复，与较大形状的数组相匹配

### 判断能否进行广播运算规则
- 将两个数组的维度大小右对齐，然后比较对应维度上的数值。
- 如果数值相等或其中一个为1或者为空，则能进行广播运算。
- 输出的维度大小为取数值大的数值。否则不能进行数组运算。

In [33]:
a = np.array([[0,0,0],[1,2,3]])
b = np.array([1,1,1])
print(a + b)

[[1 1 1]
 [2 3 4]]


In [34]:
# 不满足第二条
a = np.array([[0,0,0],[1,2,3]])
b = np.array([1,1])
print(a + b)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 