In [2]:
import numpy as np

# array创建数组

In [5]:
# array()函数，括号内可以是列表，元组，数组，迭代对象，生成器等
# 数组对象与类C语言的数组特性相同
np.array([1,2,3,4,5])
# type(np.array([1,2,3,4,5]))  numpy.ndarray

array([1, 2, 3, 4, 5])

In [6]:
#元组
np.array((1,2,3,4,5))

array([1, 2, 3, 4, 5])

In [8]:
a = np.array([1,2,3,4,5])
#数组
np.array(a)

array([1, 2, 3, 4, 5])

In [9]:
# 迭代对象
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# 生成器
np.array([i ** 2 for i in range(10)])

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

### 练习1
    创建10以内的偶数的数组

In [12]:
# np.array(range(0,10,2))
np.array([i for i in range(10) if i % 2 == 0])

array([0, 2, 4, 6, 8])

In [13]:
# dtype参数指定元素类型
#因为数组对象中的元素类型相同，若定义时出现不一样类型的元素，则其他类型元素都变成占内存空间最大的类型
np.array([1,1.5,3,4.5,'5']) #字符串占内存空间最大，其他元素都变成字符串类型

array(['1', '1.5', '3', '4.5', '5'], dtype='<U32')

In [15]:
ar3 = np.array([
    [1,2,3],
    ('a','b','c')
])# 二维数组：嵌套序列
ar3 # 列表占内存空间最大，元组就变成列表

array([['1', '2', '3'],
       ['a', 'b', 'c']], dtype='<U11')

In [16]:
ar4 = np.array([
    [1,2,3],
    ('a','b','c','d')
])# 嵌套数量不一样
ar4 #dtype=object,且已经不是二维，强制变成一维

array([list([1, 2, 3]), ('a', 'b', 'c', 'd')], dtype=object)

In [13]:
# astype() 方法强制改变数组副本的元素类型，并不改变原数组
a = np.array([1.1,1.2])
print(a.dtype)
b = a.astype('float32')
print(b.dtype)
print(a.dtype)

float64
float32
float64


In [17]:
ar4.ndim

1

In [18]:
ar4.shape #以元组的形式返回各个层次中的维度

(2,)

In [3]:
# reshape() 方法可以改变数组的维度，且返回一个副本，不改变数组
a = np.arange(20).reshape((4,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
# resize(a,new_shape) 如果新数组大于原始数组，则新数组将填充a的重复副本
a = np.array([[0,1],[2,3]])
b_2_3 = np.resize(a,(2,3))
b_2_3

array([[0, 1, 2],
       [3, 0, 1]])

In [8]:
# a.resize(new_shape)与双参数不同，此方法用0填充
a.resize((3,4),refcheck = False)
a

array([[0, 1, 2, 3],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
#itemsize 属性以字节的形式返回数组中每一个元素的大小
a = np.array([1.2,1.3])
print('类型：',a.dtype,'itemsize：',a.itemsize)

类型： float64 itemsize： 8


In [19]:
#设置dype参数，默认自动识别
a = np.array([1,2,3,4,5])
print(a)
# 设置数组元素类型
has_dtype_a = np.array([1,2,3,4,5],dtype = 'float')# 强制将int转成float
has_dtype_a

[1 2 3 4 5]


array([1., 2., 3., 4., 5.])

In [20]:
np.array([1.2, 2.3, 3.2, 4.1, 5.6],dtype = 'int') #强制将float转成int，直接取整，会丢失精度

array([1, 2, 3, 4, 5])

In [21]:
#设置copy参数，默认为True
a = np.array([1,2,3,4,5])
# 定义b，复制a
b = np.array(a)  # 若copy参数为false，则变为引用操作
#输出a和b的id
print('a:',id(a),'b:',id(b))

a: 2264527289280 b: 2264527296432


In [23]:
#设置copy参数，默认为True
a = np.array([1,2,3,4,5],copy = False)
# 定义b，复制a
b = np.array(a)  # 若copy参数为false，则变为引用操作,puthon原生是引用  《==》 b = a
#输出a和b的id
print('a:',id(a),'b:',id(b))

a: 2264527259808 b: 2264527289680


In [24]:
#ndmin 用于指定数组的维度
a = np.array([1,2,3])
print(a)
a = np.array([1,2,3],ndmin = 2) #通过直接嵌套，增加维数
a

[1 2 3]


array([[1, 2, 3]])

In [11]:
# size 属性与len方法不同，len方法只能求得最外层的元素个数
# size属性可以得到所有元素的个数
a = np.array([[0,1],[2,3]])
print(len(a))
print(a.size)

2
4


In [25]:
#subok参数，类型为bool值，默认False.
# 为True，使用object的内部数据类型；False：使用数组的数据类型
# 创建一个矩阵
a = np.mat([1,2,3,4])
#输出为矩阵类型
print(type(a))

#既要复制一个副本，又要保持原类型
at = np.array(a,subok = True)
af = np.array(a)
print(type(at))
print(type(af))

<class 'numpy.matrix'>
<class 'numpy.matrix'>
<class 'numpy.ndarray'>
