In [1]:
import numpy as np

## 求平均值mean() 或者np.mean()

In [2]:
m1 = np.arange(20).reshape((4,5))
print(m1)
# 默认求出数组的所有元素的平均值
m1.mean()

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


9.5

In [3]:
# 若相求某一维度的平均值，需要设置axis参数
# axis = 0，将从上往下计算
# axis = 1，将从左往右计算
m1.mean(axis = 0)

array([ 7.5,  8.5,  9.5, 10.5, 11.5])

In [4]:
m1.mean(axis = 1)

array([ 2.,  7., 12., 17.])

## 中位数 np.median()

In [20]:
np.median(m1)

9.5

In [7]:
ar1 = np.array([1,3,5,7,9,12])
np.median(ar1)

6.0

## 求标准差 np.std() 或者std()

In [14]:
print(np.std(m1))
print(m1.std())
print(np.std(ar1))

5.766281297335398
5.766281297335398
3.670452590924207


In [12]:
import math
# 按步骤计算标准差,先将平方差总体相加再 / n，这样与库函数的计算结果相同
math.sqrt(np.sum((ar1 - np.mean(ar1)) ** 2) / ar1.size)

3.670452590924207

## 方差np.var() 或者var()

In [16]:
print(np.var(m1))
print(m1.var())
print(np.var(ar1))

33.25
33.25
13.472222222222223


## 求最大（小）值，求和：max()，min()，sum()

In [17]:
print(m1.max())
print('axis = 0,从上往下查找：',m1.max(axis = 0))
print('axis = 1,从左往右查找：',m1.max(axis = 1))

19
axis = 0,从上往下查找： [15 16 17 18 19]
axis = 1,从左往右查找： [ 4  9 14 19]


In [18]:
print(m1.min())
print('axis = 0,从上往下查找：',m1.min(axis = 0))
print('axis = 1,从左往右查找：',m1.min(axis = 1))

0
axis = 0,从上往下查找： [0 1 2 3 4]
axis = 1,从左往右查找： [ 0  5 10 15]


In [19]:
print(m1.sum())
print('axis = 0,从上往下查找：',m1.sum(axis = 0))
print('axis = 1,从左往右查找：',m1.sum(axis = 1))

190
axis = 0,从上往下查找： [30 34 38 42 46]
axis = 1,从左往右查找： [10 35 60 85]


## 加权平均值 np.average()
   np.average(a,axis = None,weights = None,returned = False)
   无权重时与mean()方法相同

In [21]:
# 实例，考试成绩的计算
xiaoming = np.array([80,90,95])
xiaogang = np.array([95,90,80])

# 权重
weights = np.array([0.2,0.3,0.5])
# 计算xiaoming和xiaogang的平均值
print(np.mean(xiaoming))
print(np.mean(xiaogang))

#计算加权平均值
print(np.average(xiaoming,weights = weights))
print(np.average(xiaogang,weights = weights))

88.33333333333333
88.33333333333333
90.5
86.0
