In [1]:
import numpy as np
# zeros 用于创建全0数组
# 参数为shape，dtype，order

In [2]:
# 默认为float型
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros(5,dtype = int)

array([0, 0, 0, 0, 0])

In [8]:
# 2行3列的全0数组 ，2维
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# 2块2行3列的全0数组，3维
np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
# np.zeros_like用于创建与参数相同维度的全0数组
ar1 = np.array([[1,2,3],[4,5,6]])
np.zeros_like(ar1)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
# ones 用于创建全1数组，与zeros相同，同样也有ones_like函数