In [1]:
import numpy as np

In [2]:
# 与原生的python语法相同
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 比原生python高级的地方
np.arange(3.1)

array([0., 1., 2., 3.])

In [4]:
range(3.1)# 出现错误，range的参数必须是int

TypeError: 'float' object cannot be interpreted as an integer

In [5]:
# 也可以直接指定类型
x = np.arange(5,dtype = float)
x

array([0., 1., 2., 3., 4.])

In [6]:
# 起始值，终止值，步长，不包含终止值
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [8]:
# 若只有一个默认参数时，那这个参数指定为stop，若多个默认参数，则按照顺序分配参数
np.arange(20,step = 3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [9]:
# 求长度
len(np.arange(0,200,3))

67

### float型会导致误差