In [1]:
import numpy as np

In [2]:
# logspace 用于创建等比数列 ，与等差数列的参数唯一不同的是将retstep 换成 base(对数log的底数)

In [3]:
# 结果是 base 的 start - stop的幂值
a = np.logspace(0,9,10,base = 2)
a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [4]:
# 先将1 - 5分成3等分，得到1，3，5
# 再求得结果2^1,2^3,2^5
np.logspace(1,5,3,base = 2)

array([ 2.,  8., 32.])

In [5]:
np.logspace(1.0,2.0,10) # base值默认为10

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [6]:
# 等价于上式
a = np.linspace(1.0,2.0,10)
print(a)
10 ** a

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])